spring.application.name=homeserver
server.port=8100

# Db config
spring.datasource.url=jdbc:sqlite:app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.config.import=optional:classpath:application-private.properties

# Upload limit of 4MB with max error handling of 64MB.
# TODO: Uploads > 64MB sadly send an empty page, so the browser gets stuck at /cloud/upload
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB
server.tomcat.max-http-form-post-size=4MB
server.tomcat.max-swallow-size=64MB